import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Toaster} from 'react-hot-toast';
import {Providers} from "@/lib/redux/provider";
import {AuthProvider} from "@/auth/context/jwt";
import {NextAuthProvider} from "@/app/providers";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
            <Toaster/>
            <Providers>
                <NextAuthProvider>
                    <AuthProvider>
                        {children}
                    </AuthProvider>
                </NextAuthProvider>
            </Providers>
        </body>
        </html>
    )
}
